
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Article
 * 
 */
export type Article = Prisma.ArticleModel
/**
 * Model Docs
 * 
 */
export type Docs = Prisma.DocsModel
/**
 * Model File
 * 
 */
export type File = Prisma.FileModel
/**
 * Model Policy
 * 
 */
export type Policy = Prisma.PolicyModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model ProjectGroup
 * 
 */
export type ProjectGroup = Prisma.ProjectGroupModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Version
 * 
 */
export type Version = Prisma.VersionModel
