
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Docs` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Docs
 * 
 */
export type DocsModel = runtime.Types.Result.DefaultSelection<Prisma.$DocsPayload>

export type AggregateDocs = {
  _count: DocsCountAggregateOutputType | null
  _min: DocsMinAggregateOutputType | null
  _max: DocsMaxAggregateOutputType | null
}

export type DocsMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  content: string | null
  slug: string | null
  projectId: string | null
}

export type DocsMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  content: string | null
  slug: string | null
  projectId: string | null
}

export type DocsCountAggregateOutputType = {
  id: number
  title: number
  description: number
  content: number
  slug: number
  keywords: number
  projectId: number
  _all: number
}


export type DocsMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  content?: true
  slug?: true
  projectId?: true
}

export type DocsMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  content?: true
  slug?: true
  projectId?: true
}

export type DocsCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  content?: true
  slug?: true
  keywords?: true
  projectId?: true
  _all?: true
}

export type DocsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Docs to aggregate.
   */
  where?: Prisma.DocsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Docs to fetch.
   */
  orderBy?: Prisma.DocsOrderByWithRelationInput | Prisma.DocsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DocsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Docs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Docs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Docs
  **/
  _count?: true | DocsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DocsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DocsMaxAggregateInputType
}

export type GetDocsAggregateType<T extends DocsAggregateArgs> = {
      [P in keyof T & keyof AggregateDocs]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDocs[P]>
    : Prisma.GetScalarType<T[P], AggregateDocs[P]>
}




export type DocsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocsWhereInput
  orderBy?: Prisma.DocsOrderByWithAggregationInput | Prisma.DocsOrderByWithAggregationInput[]
  by: Prisma.DocsScalarFieldEnum[] | Prisma.DocsScalarFieldEnum
  having?: Prisma.DocsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DocsCountAggregateInputType | true
  _min?: DocsMinAggregateInputType
  _max?: DocsMaxAggregateInputType
}

export type DocsGroupByOutputType = {
  id: string
  title: string
  description: string
  content: string
  slug: string
  keywords: string[]
  projectId: string | null
  _count: DocsCountAggregateOutputType | null
  _min: DocsMinAggregateOutputType | null
  _max: DocsMaxAggregateOutputType | null
}

export type GetDocsGroupByPayload<T extends DocsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DocsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DocsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DocsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DocsGroupByOutputType[P]>
      }
    >
  >



export type DocsWhereInput = {
  AND?: Prisma.DocsWhereInput | Prisma.DocsWhereInput[]
  OR?: Prisma.DocsWhereInput[]
  NOT?: Prisma.DocsWhereInput | Prisma.DocsWhereInput[]
  id?: Prisma.StringFilter<"Docs"> | string
  title?: Prisma.StringFilter<"Docs"> | string
  description?: Prisma.StringFilter<"Docs"> | string
  content?: Prisma.StringFilter<"Docs"> | string
  slug?: Prisma.StringFilter<"Docs"> | string
  keywords?: Prisma.StringNullableListFilter<"Docs">
  projectId?: Prisma.StringNullableFilter<"Docs"> | string | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
}

export type DocsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  content?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type DocsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.DocsWhereInput | Prisma.DocsWhereInput[]
  OR?: Prisma.DocsWhereInput[]
  NOT?: Prisma.DocsWhereInput | Prisma.DocsWhereInput[]
  title?: Prisma.StringFilter<"Docs"> | string
  description?: Prisma.StringFilter<"Docs"> | string
  content?: Prisma.StringFilter<"Docs"> | string
  keywords?: Prisma.StringNullableListFilter<"Docs">
  projectId?: Prisma.StringNullableFilter<"Docs"> | string | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
}, "id" | "slug">

export type DocsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  content?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DocsCountOrderByAggregateInput
  _max?: Prisma.DocsMaxOrderByAggregateInput
  _min?: Prisma.DocsMinOrderByAggregateInput
}

export type DocsScalarWhereWithAggregatesInput = {
  AND?: Prisma.DocsScalarWhereWithAggregatesInput | Prisma.DocsScalarWhereWithAggregatesInput[]
  OR?: Prisma.DocsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DocsScalarWhereWithAggregatesInput | Prisma.DocsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Docs"> | string
  title?: Prisma.StringWithAggregatesFilter<"Docs"> | string
  description?: Prisma.StringWithAggregatesFilter<"Docs"> | string
  content?: Prisma.StringWithAggregatesFilter<"Docs"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Docs"> | string
  keywords?: Prisma.StringNullableListFilter<"Docs">
  projectId?: Prisma.StringNullableWithAggregatesFilter<"Docs"> | string | null
}

export type DocsCreateInput = {
  id?: string
  title: string
  description: string
  content: string
  slug: string
  keywords?: Prisma.DocsCreatekeywordsInput | string[]
  project?: Prisma.ProjectCreateNestedOneWithoutDocsInput
}

export type DocsUncheckedCreateInput = {
  id?: string
  title: string
  description: string
  content: string
  slug: string
  keywords?: Prisma.DocsCreatekeywordsInput | string[]
  projectId?: string | null
}

export type DocsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.DocsUpdatekeywordsInput | string[]
  project?: Prisma.ProjectUpdateOneWithoutDocsNestedInput
}

export type DocsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.DocsUpdatekeywordsInput | string[]
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DocsCreateManyInput = {
  id?: string
  title: string
  description: string
  content: string
  slug: string
  keywords?: Prisma.DocsCreatekeywordsInput | string[]
  projectId?: string | null
}

export type DocsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.DocsUpdatekeywordsInput | string[]
}

export type DocsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.DocsUpdatekeywordsInput | string[]
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DocsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  content?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
}

export type DocsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  content?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
}

export type DocsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  content?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
}

export type DocsListRelationFilter = {
  every?: Prisma.DocsWhereInput
  some?: Prisma.DocsWhereInput
  none?: Prisma.DocsWhereInput
}

export type DocsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DocsCreatekeywordsInput = {
  set: string[]
}

export type DocsUpdatekeywordsInput = {
  set?: string[]
  push?: string | string[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DocsCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.DocsCreateWithoutProjectInput, Prisma.DocsUncheckedCreateWithoutProjectInput> | Prisma.DocsCreateWithoutProjectInput[] | Prisma.DocsUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DocsCreateOrConnectWithoutProjectInput | Prisma.DocsCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.DocsCreateManyProjectInputEnvelope
  connect?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
}

export type DocsUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.DocsCreateWithoutProjectInput, Prisma.DocsUncheckedCreateWithoutProjectInput> | Prisma.DocsCreateWithoutProjectInput[] | Prisma.DocsUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DocsCreateOrConnectWithoutProjectInput | Prisma.DocsCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.DocsCreateManyProjectInputEnvelope
  connect?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
}

export type DocsUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.DocsCreateWithoutProjectInput, Prisma.DocsUncheckedCreateWithoutProjectInput> | Prisma.DocsCreateWithoutProjectInput[] | Prisma.DocsUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DocsCreateOrConnectWithoutProjectInput | Prisma.DocsCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.DocsUpsertWithWhereUniqueWithoutProjectInput | Prisma.DocsUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.DocsCreateManyProjectInputEnvelope
  set?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
  disconnect?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
  delete?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
  connect?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
  update?: Prisma.DocsUpdateWithWhereUniqueWithoutProjectInput | Prisma.DocsUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.DocsUpdateManyWithWhereWithoutProjectInput | Prisma.DocsUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.DocsScalarWhereInput | Prisma.DocsScalarWhereInput[]
}

export type DocsUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.DocsCreateWithoutProjectInput, Prisma.DocsUncheckedCreateWithoutProjectInput> | Prisma.DocsCreateWithoutProjectInput[] | Prisma.DocsUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DocsCreateOrConnectWithoutProjectInput | Prisma.DocsCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.DocsUpsertWithWhereUniqueWithoutProjectInput | Prisma.DocsUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.DocsCreateManyProjectInputEnvelope
  set?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
  disconnect?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
  delete?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
  connect?: Prisma.DocsWhereUniqueInput | Prisma.DocsWhereUniqueInput[]
  update?: Prisma.DocsUpdateWithWhereUniqueWithoutProjectInput | Prisma.DocsUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.DocsUpdateManyWithWhereWithoutProjectInput | Prisma.DocsUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.DocsScalarWhereInput | Prisma.DocsScalarWhereInput[]
}

export type DocsCreateWithoutProjectInput = {
  id?: string
  title: string
  description: string
  content: string
  slug: string
  keywords?: Prisma.DocsCreatekeywordsInput | string[]
}

export type DocsUncheckedCreateWithoutProjectInput = {
  id?: string
  title: string
  description: string
  content: string
  slug: string
  keywords?: Prisma.DocsCreatekeywordsInput | string[]
}

export type DocsCreateOrConnectWithoutProjectInput = {
  where: Prisma.DocsWhereUniqueInput
  create: Prisma.XOR<Prisma.DocsCreateWithoutProjectInput, Prisma.DocsUncheckedCreateWithoutProjectInput>
}

export type DocsCreateManyProjectInputEnvelope = {
  data: Prisma.DocsCreateManyProjectInput | Prisma.DocsCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type DocsUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.DocsWhereUniqueInput
  update: Prisma.XOR<Prisma.DocsUpdateWithoutProjectInput, Prisma.DocsUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.DocsCreateWithoutProjectInput, Prisma.DocsUncheckedCreateWithoutProjectInput>
}

export type DocsUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.DocsWhereUniqueInput
  data: Prisma.XOR<Prisma.DocsUpdateWithoutProjectInput, Prisma.DocsUncheckedUpdateWithoutProjectInput>
}

export type DocsUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.DocsScalarWhereInput
  data: Prisma.XOR<Prisma.DocsUpdateManyMutationInput, Prisma.DocsUncheckedUpdateManyWithoutProjectInput>
}

export type DocsScalarWhereInput = {
  AND?: Prisma.DocsScalarWhereInput | Prisma.DocsScalarWhereInput[]
  OR?: Prisma.DocsScalarWhereInput[]
  NOT?: Prisma.DocsScalarWhereInput | Prisma.DocsScalarWhereInput[]
  id?: Prisma.StringFilter<"Docs"> | string
  title?: Prisma.StringFilter<"Docs"> | string
  description?: Prisma.StringFilter<"Docs"> | string
  content?: Prisma.StringFilter<"Docs"> | string
  slug?: Prisma.StringFilter<"Docs"> | string
  keywords?: Prisma.StringNullableListFilter<"Docs">
  projectId?: Prisma.StringNullableFilter<"Docs"> | string | null
}

export type DocsCreateManyProjectInput = {
  id?: string
  title: string
  description: string
  content: string
  slug: string
  keywords?: Prisma.DocsCreatekeywordsInput | string[]
}

export type DocsUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.DocsUpdatekeywordsInput | string[]
}

export type DocsUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.DocsUpdatekeywordsInput | string[]
}

export type DocsUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.DocsUpdatekeywordsInput | string[]
}



export type DocsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  content?: boolean
  slug?: boolean
  keywords?: boolean
  projectId?: boolean
  project?: boolean | Prisma.Docs$projectArgs<ExtArgs>
}, ExtArgs["result"]["docs"]>

export type DocsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  content?: boolean
  slug?: boolean
  keywords?: boolean
  projectId?: boolean
  project?: boolean | Prisma.Docs$projectArgs<ExtArgs>
}, ExtArgs["result"]["docs"]>

export type DocsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  content?: boolean
  slug?: boolean
  keywords?: boolean
  projectId?: boolean
  project?: boolean | Prisma.Docs$projectArgs<ExtArgs>
}, ExtArgs["result"]["docs"]>

export type DocsSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  content?: boolean
  slug?: boolean
  keywords?: boolean
  projectId?: boolean
}

export type DocsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "content" | "slug" | "keywords" | "projectId", ExtArgs["result"]["docs"]>
export type DocsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.Docs$projectArgs<ExtArgs>
}
export type DocsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.Docs$projectArgs<ExtArgs>
}
export type DocsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.Docs$projectArgs<ExtArgs>
}

export type $DocsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Docs"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string
    content: string
    slug: string
    keywords: string[]
    projectId: string | null
  }, ExtArgs["result"]["docs"]>
  composites: {}
}

export type DocsGetPayload<S extends boolean | null | undefined | DocsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DocsPayload, S>

export type DocsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DocsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DocsCountAggregateInputType | true
  }

export interface DocsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Docs'], meta: { name: 'Docs' } }
  /**
   * Find zero or one Docs that matches the filter.
   * @param {DocsFindUniqueArgs} args - Arguments to find a Docs
   * @example
   * // Get one Docs
   * const docs = await prisma.docs.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DocsFindUniqueArgs>(args: Prisma.SelectSubset<T, DocsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DocsClient<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Docs that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DocsFindUniqueOrThrowArgs} args - Arguments to find a Docs
   * @example
   * // Get one Docs
   * const docs = await prisma.docs.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DocsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DocsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocsClient<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Docs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocsFindFirstArgs} args - Arguments to find a Docs
   * @example
   * // Get one Docs
   * const docs = await prisma.docs.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DocsFindFirstArgs>(args?: Prisma.SelectSubset<T, DocsFindFirstArgs<ExtArgs>>): Prisma.Prisma__DocsClient<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Docs that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocsFindFirstOrThrowArgs} args - Arguments to find a Docs
   * @example
   * // Get one Docs
   * const docs = await prisma.docs.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DocsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DocsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocsClient<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Docs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Docs
   * const docs = await prisma.docs.findMany()
   * 
   * // Get first 10 Docs
   * const docs = await prisma.docs.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const docsWithIdOnly = await prisma.docs.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DocsFindManyArgs>(args?: Prisma.SelectSubset<T, DocsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Docs.
   * @param {DocsCreateArgs} args - Arguments to create a Docs.
   * @example
   * // Create one Docs
   * const Docs = await prisma.docs.create({
   *   data: {
   *     // ... data to create a Docs
   *   }
   * })
   * 
   */
  create<T extends DocsCreateArgs>(args: Prisma.SelectSubset<T, DocsCreateArgs<ExtArgs>>): Prisma.Prisma__DocsClient<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Docs.
   * @param {DocsCreateManyArgs} args - Arguments to create many Docs.
   * @example
   * // Create many Docs
   * const docs = await prisma.docs.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DocsCreateManyArgs>(args?: Prisma.SelectSubset<T, DocsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Docs and returns the data saved in the database.
   * @param {DocsCreateManyAndReturnArgs} args - Arguments to create many Docs.
   * @example
   * // Create many Docs
   * const docs = await prisma.docs.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Docs and only return the `id`
   * const docsWithIdOnly = await prisma.docs.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DocsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DocsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Docs.
   * @param {DocsDeleteArgs} args - Arguments to delete one Docs.
   * @example
   * // Delete one Docs
   * const Docs = await prisma.docs.delete({
   *   where: {
   *     // ... filter to delete one Docs
   *   }
   * })
   * 
   */
  delete<T extends DocsDeleteArgs>(args: Prisma.SelectSubset<T, DocsDeleteArgs<ExtArgs>>): Prisma.Prisma__DocsClient<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Docs.
   * @param {DocsUpdateArgs} args - Arguments to update one Docs.
   * @example
   * // Update one Docs
   * const docs = await prisma.docs.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DocsUpdateArgs>(args: Prisma.SelectSubset<T, DocsUpdateArgs<ExtArgs>>): Prisma.Prisma__DocsClient<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Docs.
   * @param {DocsDeleteManyArgs} args - Arguments to filter Docs to delete.
   * @example
   * // Delete a few Docs
   * const { count } = await prisma.docs.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DocsDeleteManyArgs>(args?: Prisma.SelectSubset<T, DocsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Docs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Docs
   * const docs = await prisma.docs.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DocsUpdateManyArgs>(args: Prisma.SelectSubset<T, DocsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Docs and returns the data updated in the database.
   * @param {DocsUpdateManyAndReturnArgs} args - Arguments to update many Docs.
   * @example
   * // Update many Docs
   * const docs = await prisma.docs.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Docs and only return the `id`
   * const docsWithIdOnly = await prisma.docs.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DocsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DocsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Docs.
   * @param {DocsUpsertArgs} args - Arguments to update or create a Docs.
   * @example
   * // Update or create a Docs
   * const docs = await prisma.docs.upsert({
   *   create: {
   *     // ... data to create a Docs
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Docs we want to update
   *   }
   * })
   */
  upsert<T extends DocsUpsertArgs>(args: Prisma.SelectSubset<T, DocsUpsertArgs<ExtArgs>>): Prisma.Prisma__DocsClient<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Docs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocsCountArgs} args - Arguments to filter Docs to count.
   * @example
   * // Count the number of Docs
   * const count = await prisma.docs.count({
   *   where: {
   *     // ... the filter for the Docs we want to count
   *   }
   * })
  **/
  count<T extends DocsCountArgs>(
    args?: Prisma.Subset<T, DocsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DocsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Docs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DocsAggregateArgs>(args: Prisma.Subset<T, DocsAggregateArgs>): Prisma.PrismaPromise<GetDocsAggregateType<T>>

  /**
   * Group by Docs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DocsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DocsGroupByArgs['orderBy'] }
      : { orderBy?: DocsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DocsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDocsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Docs model
 */
readonly fields: DocsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Docs.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DocsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.Docs$projectArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Docs$projectArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Docs model
 */
export interface DocsFieldRefs {
  readonly id: Prisma.FieldRef<"Docs", 'String'>
  readonly title: Prisma.FieldRef<"Docs", 'String'>
  readonly description: Prisma.FieldRef<"Docs", 'String'>
  readonly content: Prisma.FieldRef<"Docs", 'String'>
  readonly slug: Prisma.FieldRef<"Docs", 'String'>
  readonly keywords: Prisma.FieldRef<"Docs", 'String[]'>
  readonly projectId: Prisma.FieldRef<"Docs", 'String'>
}
    

// Custom InputTypes
/**
 * Docs findUnique
 */
export type DocsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  /**
   * Filter, which Docs to fetch.
   */
  where: Prisma.DocsWhereUniqueInput
}

/**
 * Docs findUniqueOrThrow
 */
export type DocsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  /**
   * Filter, which Docs to fetch.
   */
  where: Prisma.DocsWhereUniqueInput
}

/**
 * Docs findFirst
 */
export type DocsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  /**
   * Filter, which Docs to fetch.
   */
  where?: Prisma.DocsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Docs to fetch.
   */
  orderBy?: Prisma.DocsOrderByWithRelationInput | Prisma.DocsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Docs.
   */
  cursor?: Prisma.DocsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Docs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Docs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Docs.
   */
  distinct?: Prisma.DocsScalarFieldEnum | Prisma.DocsScalarFieldEnum[]
}

/**
 * Docs findFirstOrThrow
 */
export type DocsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  /**
   * Filter, which Docs to fetch.
   */
  where?: Prisma.DocsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Docs to fetch.
   */
  orderBy?: Prisma.DocsOrderByWithRelationInput | Prisma.DocsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Docs.
   */
  cursor?: Prisma.DocsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Docs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Docs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Docs.
   */
  distinct?: Prisma.DocsScalarFieldEnum | Prisma.DocsScalarFieldEnum[]
}

/**
 * Docs findMany
 */
export type DocsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  /**
   * Filter, which Docs to fetch.
   */
  where?: Prisma.DocsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Docs to fetch.
   */
  orderBy?: Prisma.DocsOrderByWithRelationInput | Prisma.DocsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Docs.
   */
  cursor?: Prisma.DocsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Docs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Docs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Docs.
   */
  distinct?: Prisma.DocsScalarFieldEnum | Prisma.DocsScalarFieldEnum[]
}

/**
 * Docs create
 */
export type DocsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  /**
   * The data needed to create a Docs.
   */
  data: Prisma.XOR<Prisma.DocsCreateInput, Prisma.DocsUncheckedCreateInput>
}

/**
 * Docs createMany
 */
export type DocsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Docs.
   */
  data: Prisma.DocsCreateManyInput | Prisma.DocsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Docs createManyAndReturn
 */
export type DocsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * The data used to create many Docs.
   */
  data: Prisma.DocsCreateManyInput | Prisma.DocsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Docs update
 */
export type DocsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  /**
   * The data needed to update a Docs.
   */
  data: Prisma.XOR<Prisma.DocsUpdateInput, Prisma.DocsUncheckedUpdateInput>
  /**
   * Choose, which Docs to update.
   */
  where: Prisma.DocsWhereUniqueInput
}

/**
 * Docs updateMany
 */
export type DocsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Docs.
   */
  data: Prisma.XOR<Prisma.DocsUpdateManyMutationInput, Prisma.DocsUncheckedUpdateManyInput>
  /**
   * Filter which Docs to update
   */
  where?: Prisma.DocsWhereInput
  /**
   * Limit how many Docs to update.
   */
  limit?: number
}

/**
 * Docs updateManyAndReturn
 */
export type DocsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * The data used to update Docs.
   */
  data: Prisma.XOR<Prisma.DocsUpdateManyMutationInput, Prisma.DocsUncheckedUpdateManyInput>
  /**
   * Filter which Docs to update
   */
  where?: Prisma.DocsWhereInput
  /**
   * Limit how many Docs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Docs upsert
 */
export type DocsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  /**
   * The filter to search for the Docs to update in case it exists.
   */
  where: Prisma.DocsWhereUniqueInput
  /**
   * In case the Docs found by the `where` argument doesn't exist, create a new Docs with this data.
   */
  create: Prisma.XOR<Prisma.DocsCreateInput, Prisma.DocsUncheckedCreateInput>
  /**
   * In case the Docs was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DocsUpdateInput, Prisma.DocsUncheckedUpdateInput>
}

/**
 * Docs delete
 */
export type DocsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  /**
   * Filter which Docs to delete.
   */
  where: Prisma.DocsWhereUniqueInput
}

/**
 * Docs deleteMany
 */
export type DocsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Docs to delete
   */
  where?: Prisma.DocsWhereInput
  /**
   * Limit how many Docs to delete.
   */
  limit?: number
}

/**
 * Docs.project
 */
export type Docs$projectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
}

/**
 * Docs without action
 */
export type DocsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
}
