
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Project` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Project
 * 
 */
export type ProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$ProjectPayload>

export type AggregateProject = {
  _count: ProjectCountAggregateOutputType | null
  _min: ProjectMinAggregateOutputType | null
  _max: ProjectMaxAggregateOutputType | null
}

export type ProjectMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  content: string | null
  slug: string | null
  icon: string | null
  projectGroupId: string | null
}

export type ProjectMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  content: string | null
  slug: string | null
  icon: string | null
  projectGroupId: string | null
}

export type ProjectCountAggregateOutputType = {
  id: number
  title: number
  description: number
  content: number
  slug: number
  keywords: number
  category: number
  images: number
  icon: number
  projectGroupId: number
  _all: number
}


export type ProjectMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  content?: true
  slug?: true
  icon?: true
  projectGroupId?: true
}

export type ProjectMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  content?: true
  slug?: true
  icon?: true
  projectGroupId?: true
}

export type ProjectCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  content?: true
  slug?: true
  keywords?: true
  category?: true
  images?: true
  icon?: true
  projectGroupId?: true
  _all?: true
}

export type ProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Project to aggregate.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Projects
  **/
  _count?: true | ProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProjectMaxAggregateInputType
}

export type GetProjectAggregateType<T extends ProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProject[P]>
    : Prisma.GetScalarType<T[P], AggregateProject[P]>
}




export type ProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectWhereInput
  orderBy?: Prisma.ProjectOrderByWithAggregationInput | Prisma.ProjectOrderByWithAggregationInput[]
  by: Prisma.ProjectScalarFieldEnum[] | Prisma.ProjectScalarFieldEnum
  having?: Prisma.ProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProjectCountAggregateInputType | true
  _min?: ProjectMinAggregateInputType
  _max?: ProjectMaxAggregateInputType
}

export type ProjectGroupByOutputType = {
  id: string
  title: string
  description: string | null
  content: string | null
  slug: string
  keywords: string[]
  category: string[]
  images: string[]
  icon: string | null
  projectGroupId: string | null
  _count: ProjectCountAggregateOutputType | null
  _min: ProjectMinAggregateOutputType | null
  _max: ProjectMaxAggregateOutputType | null
}

export type GetProjectGroupByPayload<T extends ProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProjectGroupByOutputType[P]>
      }
    >
  >



export type ProjectWhereInput = {
  AND?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  OR?: Prisma.ProjectWhereInput[]
  NOT?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  id?: Prisma.StringFilter<"Project"> | string
  title?: Prisma.StringFilter<"Project"> | string
  description?: Prisma.StringNullableFilter<"Project"> | string | null
  content?: Prisma.StringNullableFilter<"Project"> | string | null
  slug?: Prisma.StringFilter<"Project"> | string
  keywords?: Prisma.StringNullableListFilter<"Project">
  category?: Prisma.StringNullableListFilter<"Project">
  images?: Prisma.StringNullableListFilter<"Project">
  icon?: Prisma.StringNullableFilter<"Project"> | string | null
  projectGroupId?: Prisma.StringNullableFilter<"Project"> | string | null
  files?: Prisma.FileListRelationFilter
  docs?: Prisma.DocsListRelationFilter
  policies?: Prisma.PolicyListRelationFilter
  projectGroup?: Prisma.XOR<Prisma.ProjectGroupNullableScalarRelationFilter, Prisma.ProjectGroupWhereInput> | null
}

export type ProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  slug?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  category?: Prisma.SortOrder
  images?: Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  projectGroupId?: Prisma.SortOrderInput | Prisma.SortOrder
  files?: Prisma.FileOrderByRelationAggregateInput
  docs?: Prisma.DocsOrderByRelationAggregateInput
  policies?: Prisma.PolicyOrderByRelationAggregateInput
  projectGroup?: Prisma.ProjectGroupOrderByWithRelationInput
}

export type ProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  OR?: Prisma.ProjectWhereInput[]
  NOT?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  title?: Prisma.StringFilter<"Project"> | string
  description?: Prisma.StringNullableFilter<"Project"> | string | null
  content?: Prisma.StringNullableFilter<"Project"> | string | null
  keywords?: Prisma.StringNullableListFilter<"Project">
  category?: Prisma.StringNullableListFilter<"Project">
  images?: Prisma.StringNullableListFilter<"Project">
  icon?: Prisma.StringNullableFilter<"Project"> | string | null
  projectGroupId?: Prisma.StringNullableFilter<"Project"> | string | null
  files?: Prisma.FileListRelationFilter
  docs?: Prisma.DocsListRelationFilter
  policies?: Prisma.PolicyListRelationFilter
  projectGroup?: Prisma.XOR<Prisma.ProjectGroupNullableScalarRelationFilter, Prisma.ProjectGroupWhereInput> | null
}, "id" | "slug">

export type ProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  slug?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  category?: Prisma.SortOrder
  images?: Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  projectGroupId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProjectCountOrderByAggregateInput
  _max?: Prisma.ProjectMaxOrderByAggregateInput
  _min?: Prisma.ProjectMinOrderByAggregateInput
}

export type ProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProjectScalarWhereWithAggregatesInput | Prisma.ProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProjectScalarWhereWithAggregatesInput | Prisma.ProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Project"> | string
  title?: Prisma.StringWithAggregatesFilter<"Project"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  content?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  slug?: Prisma.StringWithAggregatesFilter<"Project"> | string
  keywords?: Prisma.StringNullableListFilter<"Project">
  category?: Prisma.StringNullableListFilter<"Project">
  images?: Prisma.StringNullableListFilter<"Project">
  icon?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  projectGroupId?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
}

export type ProjectCreateInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  files?: Prisma.FileCreateNestedManyWithoutProjectInput
  docs?: Prisma.DocsCreateNestedManyWithoutProjectInput
  policies?: Prisma.PolicyCreateNestedManyWithoutProjectInput
  projectGroup?: Prisma.ProjectGroupCreateNestedOneWithoutProjectsInput
}

export type ProjectUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  projectGroupId?: string | null
  files?: Prisma.FileUncheckedCreateNestedManyWithoutProjectInput
  docs?: Prisma.DocsUncheckedCreateNestedManyWithoutProjectInput
  policies?: Prisma.PolicyUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.FileUpdateManyWithoutProjectNestedInput
  docs?: Prisma.DocsUpdateManyWithoutProjectNestedInput
  policies?: Prisma.PolicyUpdateManyWithoutProjectNestedInput
  projectGroup?: Prisma.ProjectGroupUpdateOneWithoutProjectsNestedInput
}

export type ProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectGroupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.FileUncheckedUpdateManyWithoutProjectNestedInput
  docs?: Prisma.DocsUncheckedUpdateManyWithoutProjectNestedInput
  policies?: Prisma.PolicyUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  projectGroupId?: string | null
}

export type ProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectGroupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProjectNullableScalarRelationFilter = {
  is?: Prisma.ProjectWhereInput | null
  isNot?: Prisma.ProjectWhereInput | null
}

export type ProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  content?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  category?: Prisma.SortOrder
  images?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  projectGroupId?: Prisma.SortOrder
}

export type ProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  content?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  projectGroupId?: Prisma.SortOrder
}

export type ProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  content?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  projectGroupId?: Prisma.SortOrder
}

export type ProjectListRelationFilter = {
  every?: Prisma.ProjectWhereInput
  some?: Prisma.ProjectWhereInput
  none?: Prisma.ProjectWhereInput
}

export type ProjectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProjectCreateNestedOneWithoutDocsInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutDocsInput, Prisma.ProjectUncheckedCreateWithoutDocsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutDocsInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneWithoutDocsNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutDocsInput, Prisma.ProjectUncheckedCreateWithoutDocsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutDocsInput
  upsert?: Prisma.ProjectUpsertWithoutDocsInput
  disconnect?: Prisma.ProjectWhereInput | boolean
  delete?: Prisma.ProjectWhereInput | boolean
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutDocsInput, Prisma.ProjectUpdateWithoutDocsInput>, Prisma.ProjectUncheckedUpdateWithoutDocsInput>
}

export type ProjectCreateNestedOneWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutFilesInput, Prisma.ProjectUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutFilesInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutFilesInput, Prisma.ProjectUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutFilesInput
  upsert?: Prisma.ProjectUpsertWithoutFilesInput
  disconnect?: Prisma.ProjectWhereInput | boolean
  delete?: Prisma.ProjectWhereInput | boolean
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutFilesInput, Prisma.ProjectUpdateWithoutFilesInput>, Prisma.ProjectUncheckedUpdateWithoutFilesInput>
}

export type ProjectCreateNestedOneWithoutPoliciesInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutPoliciesInput, Prisma.ProjectUncheckedCreateWithoutPoliciesInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutPoliciesInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneWithoutPoliciesNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutPoliciesInput, Prisma.ProjectUncheckedCreateWithoutPoliciesInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutPoliciesInput
  upsert?: Prisma.ProjectUpsertWithoutPoliciesInput
  disconnect?: Prisma.ProjectWhereInput | boolean
  delete?: Prisma.ProjectWhereInput | boolean
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutPoliciesInput, Prisma.ProjectUpdateWithoutPoliciesInput>, Prisma.ProjectUncheckedUpdateWithoutPoliciesInput>
}

export type ProjectCreatekeywordsInput = {
  set: string[]
}

export type ProjectCreatecategoryInput = {
  set: string[]
}

export type ProjectCreateimagesInput = {
  set: string[]
}

export type ProjectUpdatekeywordsInput = {
  set?: string[]
  push?: string | string[]
}

export type ProjectUpdatecategoryInput = {
  set?: string[]
  push?: string | string[]
}

export type ProjectUpdateimagesInput = {
  set?: string[]
  push?: string | string[]
}

export type ProjectCreateNestedManyWithoutProjectGroupInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput> | Prisma.ProjectCreateWithoutProjectGroupInput[] | Prisma.ProjectUncheckedCreateWithoutProjectGroupInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutProjectGroupInput | Prisma.ProjectCreateOrConnectWithoutProjectGroupInput[]
  createMany?: Prisma.ProjectCreateManyProjectGroupInputEnvelope
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
}

export type ProjectUncheckedCreateNestedManyWithoutProjectGroupInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput> | Prisma.ProjectCreateWithoutProjectGroupInput[] | Prisma.ProjectUncheckedCreateWithoutProjectGroupInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutProjectGroupInput | Prisma.ProjectCreateOrConnectWithoutProjectGroupInput[]
  createMany?: Prisma.ProjectCreateManyProjectGroupInputEnvelope
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
}

export type ProjectUpdateManyWithoutProjectGroupNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput> | Prisma.ProjectCreateWithoutProjectGroupInput[] | Prisma.ProjectUncheckedCreateWithoutProjectGroupInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutProjectGroupInput | Prisma.ProjectCreateOrConnectWithoutProjectGroupInput[]
  upsert?: Prisma.ProjectUpsertWithWhereUniqueWithoutProjectGroupInput | Prisma.ProjectUpsertWithWhereUniqueWithoutProjectGroupInput[]
  createMany?: Prisma.ProjectCreateManyProjectGroupInputEnvelope
  set?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  disconnect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  delete?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  update?: Prisma.ProjectUpdateWithWhereUniqueWithoutProjectGroupInput | Prisma.ProjectUpdateWithWhereUniqueWithoutProjectGroupInput[]
  updateMany?: Prisma.ProjectUpdateManyWithWhereWithoutProjectGroupInput | Prisma.ProjectUpdateManyWithWhereWithoutProjectGroupInput[]
  deleteMany?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
}

export type ProjectUncheckedUpdateManyWithoutProjectGroupNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput> | Prisma.ProjectCreateWithoutProjectGroupInput[] | Prisma.ProjectUncheckedCreateWithoutProjectGroupInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutProjectGroupInput | Prisma.ProjectCreateOrConnectWithoutProjectGroupInput[]
  upsert?: Prisma.ProjectUpsertWithWhereUniqueWithoutProjectGroupInput | Prisma.ProjectUpsertWithWhereUniqueWithoutProjectGroupInput[]
  createMany?: Prisma.ProjectCreateManyProjectGroupInputEnvelope
  set?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  disconnect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  delete?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  update?: Prisma.ProjectUpdateWithWhereUniqueWithoutProjectGroupInput | Prisma.ProjectUpdateWithWhereUniqueWithoutProjectGroupInput[]
  updateMany?: Prisma.ProjectUpdateManyWithWhereWithoutProjectGroupInput | Prisma.ProjectUpdateManyWithWhereWithoutProjectGroupInput[]
  deleteMany?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
}

export type ProjectCreateWithoutDocsInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  files?: Prisma.FileCreateNestedManyWithoutProjectInput
  policies?: Prisma.PolicyCreateNestedManyWithoutProjectInput
  projectGroup?: Prisma.ProjectGroupCreateNestedOneWithoutProjectsInput
}

export type ProjectUncheckedCreateWithoutDocsInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  projectGroupId?: string | null
  files?: Prisma.FileUncheckedCreateNestedManyWithoutProjectInput
  policies?: Prisma.PolicyUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutDocsInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutDocsInput, Prisma.ProjectUncheckedCreateWithoutDocsInput>
}

export type ProjectUpsertWithoutDocsInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutDocsInput, Prisma.ProjectUncheckedUpdateWithoutDocsInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutDocsInput, Prisma.ProjectUncheckedCreateWithoutDocsInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutDocsInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutDocsInput, Prisma.ProjectUncheckedUpdateWithoutDocsInput>
}

export type ProjectUpdateWithoutDocsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.FileUpdateManyWithoutProjectNestedInput
  policies?: Prisma.PolicyUpdateManyWithoutProjectNestedInput
  projectGroup?: Prisma.ProjectGroupUpdateOneWithoutProjectsNestedInput
}

export type ProjectUncheckedUpdateWithoutDocsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectGroupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.FileUncheckedUpdateManyWithoutProjectNestedInput
  policies?: Prisma.PolicyUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectCreateWithoutFilesInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  docs?: Prisma.DocsCreateNestedManyWithoutProjectInput
  policies?: Prisma.PolicyCreateNestedManyWithoutProjectInput
  projectGroup?: Prisma.ProjectGroupCreateNestedOneWithoutProjectsInput
}

export type ProjectUncheckedCreateWithoutFilesInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  projectGroupId?: string | null
  docs?: Prisma.DocsUncheckedCreateNestedManyWithoutProjectInput
  policies?: Prisma.PolicyUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutFilesInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutFilesInput, Prisma.ProjectUncheckedCreateWithoutFilesInput>
}

export type ProjectUpsertWithoutFilesInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutFilesInput, Prisma.ProjectUncheckedUpdateWithoutFilesInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutFilesInput, Prisma.ProjectUncheckedCreateWithoutFilesInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutFilesInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutFilesInput, Prisma.ProjectUncheckedUpdateWithoutFilesInput>
}

export type ProjectUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs?: Prisma.DocsUpdateManyWithoutProjectNestedInput
  policies?: Prisma.PolicyUpdateManyWithoutProjectNestedInput
  projectGroup?: Prisma.ProjectGroupUpdateOneWithoutProjectsNestedInput
}

export type ProjectUncheckedUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectGroupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs?: Prisma.DocsUncheckedUpdateManyWithoutProjectNestedInput
  policies?: Prisma.PolicyUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectCreateWithoutPoliciesInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  files?: Prisma.FileCreateNestedManyWithoutProjectInput
  docs?: Prisma.DocsCreateNestedManyWithoutProjectInput
  projectGroup?: Prisma.ProjectGroupCreateNestedOneWithoutProjectsInput
}

export type ProjectUncheckedCreateWithoutPoliciesInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  projectGroupId?: string | null
  files?: Prisma.FileUncheckedCreateNestedManyWithoutProjectInput
  docs?: Prisma.DocsUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutPoliciesInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutPoliciesInput, Prisma.ProjectUncheckedCreateWithoutPoliciesInput>
}

export type ProjectUpsertWithoutPoliciesInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutPoliciesInput, Prisma.ProjectUncheckedUpdateWithoutPoliciesInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutPoliciesInput, Prisma.ProjectUncheckedCreateWithoutPoliciesInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutPoliciesInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutPoliciesInput, Prisma.ProjectUncheckedUpdateWithoutPoliciesInput>
}

export type ProjectUpdateWithoutPoliciesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.FileUpdateManyWithoutProjectNestedInput
  docs?: Prisma.DocsUpdateManyWithoutProjectNestedInput
  projectGroup?: Prisma.ProjectGroupUpdateOneWithoutProjectsNestedInput
}

export type ProjectUncheckedUpdateWithoutPoliciesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectGroupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.FileUncheckedUpdateManyWithoutProjectNestedInput
  docs?: Prisma.DocsUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectCreateWithoutProjectGroupInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  files?: Prisma.FileCreateNestedManyWithoutProjectInput
  docs?: Prisma.DocsCreateNestedManyWithoutProjectInput
  policies?: Prisma.PolicyCreateNestedManyWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutProjectGroupInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
  files?: Prisma.FileUncheckedCreateNestedManyWithoutProjectInput
  docs?: Prisma.DocsUncheckedCreateNestedManyWithoutProjectInput
  policies?: Prisma.PolicyUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutProjectGroupInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput>
}

export type ProjectCreateManyProjectGroupInputEnvelope = {
  data: Prisma.ProjectCreateManyProjectGroupInput | Prisma.ProjectCreateManyProjectGroupInput[]
  skipDuplicates?: boolean
}

export type ProjectUpsertWithWhereUniqueWithoutProjectGroupInput = {
  where: Prisma.ProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutProjectGroupInput, Prisma.ProjectUncheckedUpdateWithoutProjectGroupInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput>
}

export type ProjectUpdateWithWhereUniqueWithoutProjectGroupInput = {
  where: Prisma.ProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutProjectGroupInput, Prisma.ProjectUncheckedUpdateWithoutProjectGroupInput>
}

export type ProjectUpdateManyWithWhereWithoutProjectGroupInput = {
  where: Prisma.ProjectScalarWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyWithoutProjectGroupInput>
}

export type ProjectScalarWhereInput = {
  AND?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
  OR?: Prisma.ProjectScalarWhereInput[]
  NOT?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
  id?: Prisma.StringFilter<"Project"> | string
  title?: Prisma.StringFilter<"Project"> | string
  description?: Prisma.StringNullableFilter<"Project"> | string | null
  content?: Prisma.StringNullableFilter<"Project"> | string | null
  slug?: Prisma.StringFilter<"Project"> | string
  keywords?: Prisma.StringNullableListFilter<"Project">
  category?: Prisma.StringNullableListFilter<"Project">
  images?: Prisma.StringNullableListFilter<"Project">
  icon?: Prisma.StringNullableFilter<"Project"> | string | null
  projectGroupId?: Prisma.StringNullableFilter<"Project"> | string | null
}

export type ProjectCreateManyProjectGroupInput = {
  id?: string
  title: string
  description?: string | null
  content?: string | null
  slug: string
  keywords?: Prisma.ProjectCreatekeywordsInput | string[]
  category?: Prisma.ProjectCreatecategoryInput | string[]
  images?: Prisma.ProjectCreateimagesInput | string[]
  icon?: string | null
}

export type ProjectUpdateWithoutProjectGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.FileUpdateManyWithoutProjectNestedInput
  docs?: Prisma.DocsUpdateManyWithoutProjectNestedInput
  policies?: Prisma.PolicyUpdateManyWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutProjectGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.FileUncheckedUpdateManyWithoutProjectNestedInput
  docs?: Prisma.DocsUncheckedUpdateManyWithoutProjectNestedInput
  policies?: Prisma.PolicyUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateManyWithoutProjectGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.ProjectUpdatekeywordsInput | string[]
  category?: Prisma.ProjectUpdatecategoryInput | string[]
  images?: Prisma.ProjectUpdateimagesInput | string[]
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type ProjectCountOutputType
 */

export type ProjectCountOutputType = {
  files: number
  docs: number
  policies: number
}

export type ProjectCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | ProjectCountOutputTypeCountFilesArgs
  docs?: boolean | ProjectCountOutputTypeCountDocsArgs
  policies?: boolean | ProjectCountOutputTypeCountPoliciesArgs
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCountOutputType
   */
  select?: Prisma.ProjectCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileWhereInput
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountDocsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocsWhereInput
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountPoliciesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PolicyWhereInput
}


export type ProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  content?: boolean
  slug?: boolean
  keywords?: boolean
  category?: boolean
  images?: boolean
  icon?: boolean
  projectGroupId?: boolean
  files?: boolean | Prisma.Project$filesArgs<ExtArgs>
  docs?: boolean | Prisma.Project$docsArgs<ExtArgs>
  policies?: boolean | Prisma.Project$policiesArgs<ExtArgs>
  projectGroup?: boolean | Prisma.Project$projectGroupArgs<ExtArgs>
  _count?: boolean | Prisma.ProjectCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["project"]>

export type ProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  content?: boolean
  slug?: boolean
  keywords?: boolean
  category?: boolean
  images?: boolean
  icon?: boolean
  projectGroupId?: boolean
  projectGroup?: boolean | Prisma.Project$projectGroupArgs<ExtArgs>
}, ExtArgs["result"]["project"]>

export type ProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  content?: boolean
  slug?: boolean
  keywords?: boolean
  category?: boolean
  images?: boolean
  icon?: boolean
  projectGroupId?: boolean
  projectGroup?: boolean | Prisma.Project$projectGroupArgs<ExtArgs>
}, ExtArgs["result"]["project"]>

export type ProjectSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  content?: boolean
  slug?: boolean
  keywords?: boolean
  category?: boolean
  images?: boolean
  icon?: boolean
  projectGroupId?: boolean
}

export type ProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "content" | "slug" | "keywords" | "category" | "images" | "icon" | "projectGroupId", ExtArgs["result"]["project"]>
export type ProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | Prisma.Project$filesArgs<ExtArgs>
  docs?: boolean | Prisma.Project$docsArgs<ExtArgs>
  policies?: boolean | Prisma.Project$policiesArgs<ExtArgs>
  projectGroup?: boolean | Prisma.Project$projectGroupArgs<ExtArgs>
  _count?: boolean | Prisma.ProjectCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projectGroup?: boolean | Prisma.Project$projectGroupArgs<ExtArgs>
}
export type ProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projectGroup?: boolean | Prisma.Project$projectGroupArgs<ExtArgs>
}

export type $ProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Project"
  objects: {
    files: Prisma.$FilePayload<ExtArgs>[]
    docs: Prisma.$DocsPayload<ExtArgs>[]
    policies: Prisma.$PolicyPayload<ExtArgs>[]
    projectGroup: Prisma.$ProjectGroupPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    content: string | null
    slug: string
    keywords: string[]
    category: string[]
    images: string[]
    icon: string | null
    projectGroupId: string | null
  }, ExtArgs["result"]["project"]>
  composites: {}
}

export type ProjectGetPayload<S extends boolean | null | undefined | ProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProjectPayload, S>

export type ProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProjectCountAggregateInputType | true
  }

export interface ProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Project'], meta: { name: 'Project' } }
  /**
   * Find zero or one Project that matches the filter.
   * @param {ProjectFindUniqueArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, ProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Project that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProjectFindUniqueOrThrowArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Project that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindFirstArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, ProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Project that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindFirstOrThrowArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Projects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Projects
   * const projects = await prisma.project.findMany()
   * 
   * // Get first 10 Projects
   * const projects = await prisma.project.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const projectWithIdOnly = await prisma.project.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProjectFindManyArgs>(args?: Prisma.SelectSubset<T, ProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Project.
   * @param {ProjectCreateArgs} args - Arguments to create a Project.
   * @example
   * // Create one Project
   * const Project = await prisma.project.create({
   *   data: {
   *     // ... data to create a Project
   *   }
   * })
   * 
   */
  create<T extends ProjectCreateArgs>(args: Prisma.SelectSubset<T, ProjectCreateArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Projects.
   * @param {ProjectCreateManyArgs} args - Arguments to create many Projects.
   * @example
   * // Create many Projects
   * const project = await prisma.project.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, ProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Projects and returns the data saved in the database.
   * @param {ProjectCreateManyAndReturnArgs} args - Arguments to create many Projects.
   * @example
   * // Create many Projects
   * const project = await prisma.project.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Projects and only return the `id`
   * const projectWithIdOnly = await prisma.project.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Project.
   * @param {ProjectDeleteArgs} args - Arguments to delete one Project.
   * @example
   * // Delete one Project
   * const Project = await prisma.project.delete({
   *   where: {
   *     // ... filter to delete one Project
   *   }
   * })
   * 
   */
  delete<T extends ProjectDeleteArgs>(args: Prisma.SelectSubset<T, ProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Project.
   * @param {ProjectUpdateArgs} args - Arguments to update one Project.
   * @example
   * // Update one Project
   * const project = await prisma.project.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProjectUpdateArgs>(args: Prisma.SelectSubset<T, ProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Projects.
   * @param {ProjectDeleteManyArgs} args - Arguments to filter Projects to delete.
   * @example
   * // Delete a few Projects
   * const { count } = await prisma.project.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Projects
   * const project = await prisma.project.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, ProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projects and returns the data updated in the database.
   * @param {ProjectUpdateManyAndReturnArgs} args - Arguments to update many Projects.
   * @example
   * // Update many Projects
   * const project = await prisma.project.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Projects and only return the `id`
   * const projectWithIdOnly = await prisma.project.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Project.
   * @param {ProjectUpsertArgs} args - Arguments to update or create a Project.
   * @example
   * // Update or create a Project
   * const project = await prisma.project.upsert({
   *   create: {
   *     // ... data to create a Project
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Project we want to update
   *   }
   * })
   */
  upsert<T extends ProjectUpsertArgs>(args: Prisma.SelectSubset<T, ProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCountArgs} args - Arguments to filter Projects to count.
   * @example
   * // Count the number of Projects
   * const count = await prisma.project.count({
   *   where: {
   *     // ... the filter for the Projects we want to count
   *   }
   * })
  **/
  count<T extends ProjectCountArgs>(
    args?: Prisma.Subset<T, ProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProjectAggregateArgs>(args: Prisma.Subset<T, ProjectAggregateArgs>): Prisma.PrismaPromise<GetProjectAggregateType<T>>

  /**
   * Group by Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProjectGroupByArgs['orderBy'] }
      : { orderBy?: ProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Project model
 */
readonly fields: ProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Project.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  files<T extends Prisma.Project$filesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$filesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  docs<T extends Prisma.Project$docsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$docsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  policies<T extends Prisma.Project$policiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$policiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  projectGroup<T extends Prisma.Project$projectGroupArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$projectGroupArgs<ExtArgs>>): Prisma.Prisma__ProjectGroupClient<runtime.Types.Result.GetResult<Prisma.$ProjectGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Project model
 */
export interface ProjectFieldRefs {
  readonly id: Prisma.FieldRef<"Project", 'String'>
  readonly title: Prisma.FieldRef<"Project", 'String'>
  readonly description: Prisma.FieldRef<"Project", 'String'>
  readonly content: Prisma.FieldRef<"Project", 'String'>
  readonly slug: Prisma.FieldRef<"Project", 'String'>
  readonly keywords: Prisma.FieldRef<"Project", 'String[]'>
  readonly category: Prisma.FieldRef<"Project", 'String[]'>
  readonly images: Prisma.FieldRef<"Project", 'String[]'>
  readonly icon: Prisma.FieldRef<"Project", 'String'>
  readonly projectGroupId: Prisma.FieldRef<"Project", 'String'>
}
    

// Custom InputTypes
/**
 * Project findUnique
 */
export type ProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project findUniqueOrThrow
 */
export type ProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project findFirst
 */
export type ProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project findFirstOrThrow
 */
export type ProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project findMany
 */
export type ProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Projects to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project create
 */
export type ProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a Project.
   */
  data: Prisma.XOR<Prisma.ProjectCreateInput, Prisma.ProjectUncheckedCreateInput>
}

/**
 * Project createMany
 */
export type ProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Projects.
   */
  data: Prisma.ProjectCreateManyInput | Prisma.ProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Project createManyAndReturn
 */
export type ProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * The data used to create many Projects.
   */
  data: Prisma.ProjectCreateManyInput | Prisma.ProjectCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Project update
 */
export type ProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a Project.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateInput, Prisma.ProjectUncheckedUpdateInput>
  /**
   * Choose, which Project to update.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project updateMany
 */
export type ProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Projects.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Projects to update
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to update.
   */
  limit?: number
}

/**
 * Project updateManyAndReturn
 */
export type ProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * The data used to update Projects.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Projects to update
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Project upsert
 */
export type ProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the Project to update in case it exists.
   */
  where: Prisma.ProjectWhereUniqueInput
  /**
   * In case the Project found by the `where` argument doesn't exist, create a new Project with this data.
   */
  create: Prisma.XOR<Prisma.ProjectCreateInput, Prisma.ProjectUncheckedCreateInput>
  /**
   * In case the Project was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProjectUpdateInput, Prisma.ProjectUncheckedUpdateInput>
}

/**
 * Project delete
 */
export type ProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter which Project to delete.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project deleteMany
 */
export type ProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Projects to delete
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to delete.
   */
  limit?: number
}

/**
 * Project.files
 */
export type Project$filesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  where?: Prisma.FileWhereInput
  orderBy?: Prisma.FileOrderByWithRelationInput | Prisma.FileOrderByWithRelationInput[]
  cursor?: Prisma.FileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FileScalarFieldEnum | Prisma.FileScalarFieldEnum[]
}

/**
 * Project.docs
 */
export type Project$docsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Docs
   */
  select?: Prisma.DocsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Docs
   */
  omit?: Prisma.DocsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocsInclude<ExtArgs> | null
  where?: Prisma.DocsWhereInput
  orderBy?: Prisma.DocsOrderByWithRelationInput | Prisma.DocsOrderByWithRelationInput[]
  cursor?: Prisma.DocsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DocsScalarFieldEnum | Prisma.DocsScalarFieldEnum[]
}

/**
 * Project.policies
 */
export type Project$policiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  where?: Prisma.PolicyWhereInput
  orderBy?: Prisma.PolicyOrderByWithRelationInput | Prisma.PolicyOrderByWithRelationInput[]
  cursor?: Prisma.PolicyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PolicyScalarFieldEnum | Prisma.PolicyScalarFieldEnum[]
}

/**
 * Project.projectGroup
 */
export type Project$projectGroupArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectGroup
   */
  select?: Prisma.ProjectGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectGroup
   */
  omit?: Prisma.ProjectGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectGroupInclude<ExtArgs> | null
  where?: Prisma.ProjectGroupWhereInput
}

/**
 * Project without action
 */
export type ProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
}
